### ISSUE TITLE
Direction probleme on objectPage

### ISSUE THREAD

**Issue by jsinapayen** [nevakee716/cwNetwork#2]
Hello

I have direction issue on an objectPage
![bug](https://user-images.githubusercontent.com/33056287/31937023-93d9498a-b8b3-11e7-9ce0-8aad536b19fb.png)
![bug](https://user-images.githubusercontent.com/33056287/31937123-d22cded6-b8b3-11e7-8d27-fd373376a478.png)

Best Regards

**Comment by nevakee716** [comment]
We are working on the subject can you send your mdb model by email?

**Comment by nevakee716** [comment]
This is a problem of configuration, in the arrow direction , please use ' instead of "

**Comment by nevakee716** [comment]
close the issue
