### ISSUE TITLE
hyde element question

### ISSUE THREAD

**Issue by jsinapayen** [nevakee716/cwNetwork#3]
Bonjour Mathias,

Après quelques tests complémentaires, le symptôme est le suivant : 

Lorsque j’arrive sur une page objet processus (mgenprocessus) pour une catégorie = processus, nous avons deux cas de figure : 
•	Si le processus est modélisé (via Casewise Modeler)  l’affichage est OK
•	Si, le processus n’est pas modélisé  l’affichage est KO
o	Affichage du diagramme automatique qui de fait ne fonctionne pas puisqu’il a été paramétré pour une règle de gestion 

Voici un morceau du fichier
{ // cache la tab0 (diagramme) par default
                "action": "changeStyle",
                "style": "display",
                "styleValue": "none",
                "type" : "tab", 
                "id" : "tab0",
            },
            {  // affiche la tab0 (diagramme) si c'est un "Processus","Domaine d'activité" 
                "action": "changeStyle",
                "style": "display",
                "styleValue": "block",
                "type" : "tab", 
                "id" : "tab4",
                "property" : "type",
                "operator"  : "=",
                "value" : ["Processus","Macro-Processus","Activité"]
            },
             { // cache la tab8 (diagramme automatique) par default
                "action": "changeStyle",
                "style": "display",
                "styleValue": "none",
                "type" : "tab", 
                "id" : "tab8",
            },
            {  // affiche la tab8 (diagramme automatique) si c'est une règle de gestion 
                "action": "changeStyle",
                "style": "display",
                "styleValue": "block",
                "type" : "tab", 
                "id" : "tab8",
                "property" : "type",
                "operator"  : "=",
                "value" : "Règle de gestion"
            },

**Comment by nevakee716** [comment]
not in the right github please post your request here

https://github.com/nevakee716/HideElementIf/issues
