### ISSUE TITLE
Pas d'affichage de cluster avec des "complementary Node"

### ISSUE THREAD

**Issue by tubayolo95** [nevakee716/cwNetwork#4]
je suis en version (Network-v4.1.0-evolve-v4.1-4.2)
+ cw2016 + evolve 4.2.2

mon network permet d'afficher les "composants applicatif" d'une application.
mais je veux donner une icon différentes en fonction du type du composant
j'ai donc decoupe mes listes de composants via des associations avec des filtres par category
et défini cela en nœud complementaire ds le network, en grouplist ... et assigne un icon a chaque grouplist

![img_2018-03-13 11_14_28-frparapp51 - connexion bureau a distance](https://user-images.githubusercontent.com/37330822/37336246-ba6ec576-26a8-11e8-80ac-b5d5d565aefc.png)
![img_2018-03-13 11_14_55-frparapp51 - connexion bureau a distance](https://user-images.githubusercontent.com/37330822/37336252-bf7b9648-26a8-11e8-96ff-50a2fec6d610.png)

Nœud complementaire : 
composant_applicatif_siteweb,composant_applicatif_BdD,composant_applicatif_Cube,composant_applicatif_Traitement,composant_applicatif_MoteurApplicatif,composant_applicatif_ClientUtilitaire,composant_applicatif_Rapport,composant_applicatif_Stockage

Specific groupList : 
composant_applicatif_siteweb,ca_siteweb#composant_applicatif_autre,ca_autre#composant_applicatif_BdD,ca_BdD#composant_applicatif_Cube,ca_Cube#composant_applicatif_Traitement,ca_Traitement#composant_applicatif_MoteurApplicatif,ca_MoteurApplicatif#composant_applicatif_ClientUtilitaire,ca_ClientUtilitaire#composant_applicatif_Rapport,ca_Rapport#composant_applicatif_Stockage,ca_Stockage

Assign icon to group : ca_Rapport,icon,f0f6,#2196F3||ca_Stockage,icon,f115,#2196F3||ca_ClientUtilitaire,icon,f11c,#2196F3||ca_MoteurApplicatif,icon,f085,#2196F3||ca_Traitement,icon,f013,#2196F3||ca_Cube,icon,f1b2,#2196F3||Composant Logiciel,icon,f02b,#9e0000||ca_BdD,icon,f1c0,#2196F3||ca_siteweb,icon,f1fa,33baff||Equipement Logique,icon,f233,#008000||Application,icon,f1ad,#0D47A1||ca_autre,icon,f12e,#ffa500

Le PB : en faisant ce type de decoupage, les clusters ne fonctionnent plus
![img_2018-03-13 11_22_50-btp - internet explorer](https://user-images.githubusercontent.com/37330822/37336215-a483f2ae-26a8-11e8-9a09-e97466b5e2cc.png)

j ai refais une page sans le decoupage par type de composant => le cluster fonctionne

![img_2018-03-13 11_22_21-btp - internet explorer](https://user-images.githubusercontent.com/37330822/37336220-ac3817a0-26a8-11e8-9f50-53e4a3dc2e60.png)

merci

**Comment by nevakee716** [comment]
lorsque tu essayes de lancer la clusterisation est ce que tu as une erreur javascript?
Je viens de faire chez moi avec un configuration équivalente cela fonctionne.

**Comment by tubayolo95** [comment]
non  pas d'erreur !
je viens de refaire le test 



![img_2018-03-13 15_02_57-ebusiness suite - glf - internet explorer](https://user-images.githubusercontent.com/37330822/37346498-5fbd4e44-26c7-11e8-943a-8c1e8f3f73f7.png)

**Comment by tubayolo95** [comment]
Non , pas d'erreur

**Comment by tubayolo95** [comment]
j ai reproduit le pb 
dans le cas ou on utilise une grouplist specific, ça ne fonctionne pas 

![img_2018-03-13 19_13_08-frparapp51 - connexion bureau a distance](https://user-images.githubusercontent.com/37330822/37361486-ed40877c-26ea-11e8-91d1-1e756def8362.png)

cela donne : 
![img_2018-03-13 19_12_38-ebusiness suite - glf - internet explorer](https://user-images.githubusercontent.com/37330822/37361533-06eaa6e4-26eb-11e8-8c67-727e52306a21.png)


si je retire tout : 
![img_2018-03-13 19_19_38-frparapp51 - connexion bureau a distance](https://user-images.githubusercontent.com/37330822/37361574-257821fe-26eb-11e8-8ea0-3e4a50595107.png)

j ai alors :+1: 
![img_2018-03-13 19_15_13-ebusiness suite - glf - internet explorer](https://user-images.githubusercontent.com/37330822/37361605-3a42cdd2-26eb-11e8-9d27-9cbd54dd8295.png)

**Comment by nevakee716** [comment]
Bonjour

Le problème vient de res underscore dans les noms des groupes, enleves les et tu n'auras plus de problème

**Comment by nevakee716** [comment]
Tu peux utiliser des espaces à la place

**Comment by tubayolo95** [comment]
ok je teste cette aprem   merci

**Comment by tubayolo95** [comment]
C est bon ça marche ! merci 

![img_2018-03-14 11_28_15-ebusiness suite - glf - internet explorer](https://user-images.githubusercontent.com/37330822/37397051-8a981d32-2772-11e8-8400-32ecccb8eed2.png)
