### ISSUE TITLE
Amelioration Lisibilité 

### ISSUE THREAD

**Issue by tubayolo95** [nevakee716/cwNetwork#5]
Je pense qu'en retirant la couleur du fond du cluster ce serait plus lisible et "jolie"
et ne l'utiliser que pour les contours : 

![img_2018-03-14 13_04_35-btp - internet explorer](https://user-images.githubusercontent.com/37330822/37401561-5ce28748-2780-11e8-91a7-c1936616112b.png)
en mode cluster : 
![img_2018-03-14 13_04_25-btp - internet explorer](https://user-images.githubusercontent.com/37330822/37401562-5d0cb504-2780-11e8-9167-97769d28c020.png)

ou 

![img_2018-03-14 13_04_14-btp - internet explorer](https://user-images.githubusercontent.com/37330822/37401563-5d34ad8e-2780-11e8-9c12-775d4226febe.png)

**Comment by nevakee716** [comment]
actuellement, la couleur est défini comme étant la couleur de la head du cluster avec un éclaircissement fixe, je mettrais l'option dans le layout afin de la choisir, comme ça si tu mets 1000000% tu auras du blanc

**Comment by nevakee716** [comment]
avec la dernière mise à jour, les clusters sont à minimum 150 de luminosités, cela devrait corriger le problème
