### ISSUE TITLE
netowrk enhancement requests

### ISSUE THREAD

**Issue by otardiolo** [nevakee716/cwNetwork#8]
Hi Mathias,
we have succesfully deployed the network layout to one of our customers and I have some enhancement requests for you:
1- the site is in italian so labels are not correctly shown. Is there a way to bypass this problem (I think you already mention a workaround during one of our call but I can't remember it)
2- When deactivating a cluster, links between parent object and childs are lost
3- In the filter drop-down lists on the top, the symbol is shown only for the groups that have a fontawesome icon. It is extremely usefull to have the symbol also for the groups with standard icons in order to have a full legend on the page
4- "Focus On" dropdown list doesn't show all the objects of the diagram, but only a subset

Please let me know if you need more information.
Thank you,
Omar

**Comment by nevakee716** [comment]
splitting the issue in 4 separate issues
