### ISSUE TITLE
issue with italian site

### ISSUE THREAD

**Issue by nevakee716** [nevakee716/cwNetwork#9]
1- the site is in italian so labels are not correctly shown. Is there a way to bypass this problem (I think you already mention a workaround during one of our call but I can't remember it)

**Comment by nevakee716** [comment]
need to add the translation here
https://github.com/nevakee716/cwNetwork/blob/master/src/i18n/Fields.translations_en.txt

basically we need the same file with italien translation

**Comment by otardiolo** [comment]
thanks, you can close this issue.

Omar

**Comment by nevakee716** [comment]
can you give me the italian file so I can put that in the repository

**Comment by abovi** [comment]
[Fields.translations_it.txt](https://github.com/nevakee716/cwNetwork/files/2502051/Fields.translations_it.txt)

**Comment by nevakee716** [comment]
will be added to the 6.0 version
